local constants = {
  gravity = 1400,
  player = {
    speed = 260,
    jump_speed = 520,
    max_jumps = 2,
    coyote_time = 0.12,
    jump_buffer_time = 0.1,
    dash_speed = 520,
    dash_duration = 0.14,
    dash_cooldown = 0.6,
    hurt_cooldown = 0.6,
    width = 28,
    height = 40,
    max_health = 3,
    attack_damage = 1,
    attack_duration = 0.12,
    attack_cooldown = 0.3,
    attack_range = 26,
    attack_height = 22,
    heal_on_absorb = 1,
    heal_on_remove = 1,
    special_absorb_threshold = 3,
    special_remove_threshold = 5,
    special_range = 70,
    special_damage_offensive = 999,
    special_damage_defensive = 4,
    max_abilities = 3,
    hit_flash_duration = 0.12,
    knockback_force = 160,
  },
  enemy = {
    speed = 80,
    width = 28,
    height = 36,
    health = 2,
    damage = 1,
    agro_range = 180,
    hit_flash_duration = 0.12,
    knockback_force = 120,
  },
  boss = {
    width = 56,
    height = 70,
    damage = 1,
    agro_range = 260,
    hit_flash_duration = 0.16,
    knockback_force = 180,
  },
  pickup = {
    heal_amount = 1,
  },
}

return constants
